---
collections:
  - azure.azcollection
  - awx.awx
  - name: https://github.com/ansible-collections/cloud.azure_roles.git
    type: git
    version: main
  - name: https://github.com/scottharwell/aoc_demo_setup.git
    type: git
    version: main
