---
collections:
  - name: azure.azcollection
    version: 5.0.1
  - name: awx.awx
    version: 21.0.0
roles:
  - name: cloud.azure_roles
    src: https://github.com/ansible-collections/cloud.azure_roles.git
    scm: git
    version: main
  - name: ansible_on_clouds.aoc_demo_setup
    scm: git
    src: https://github.com/scottharwell/aoc_demo_setup.git
    version: main
